### ISSUE TITLE
Code from my zip file didn't get here.

### ISSUE THREAD

**Issue by JamieRCHI** [BraveCaperCat2/StoneWaterWell2#1]
All the files from the zip file I posted on  Onedrive are empty here. Except for the new .md file.

Let's see if this works.
[StoneWaterWell_2.20.2.zip](https://github.com/user-attachments/files/17625612/StoneWaterWell_2.20.2.zip)

**Comment by BraveCaperCat2** [comment]
This has to do with me uploading files directly from the zip. I've reuploaded the files now, the releases tab has the zip file directly attached, so it doesn't have the same problem.
